language: java
jdk:
  - oraclejdk8
install: ./mvnw install -DskipTests -Dgpg.skip
notifications:
  slack:
    secure: BP5IbGz6SROlGdhtKsr45NGWyK7EDwy28OQTN3/NhHrB+rBJpmAU9irXBu9tVwWzXMo1DkmkXAqdyE9dy4BFn5Ah1T9xuEXvMyoBwOYDNH5GlPXD5BQeF/flkW7JaZUOU53MvKpvHaHknD+5moye1/TnaG0+YvkVc1FQV9EbxYKwGDgjML77qWUO7ggmkeg9x6C9A0ry8hIzPt94mi2riFdZEGs7RNMZKnBK9wmCT2RUdZOuAAwNJTd6KnRwnNMDmGHXDylKv8aDeIyA+mYDMen1UN8A4pGw7BW7imIQ5Sp34YxhldHd4LdWZunGTUU6LA+vIIFBmMsEo1u7kU1McnKe9CDEHKrZ+JD+KV+1o+GtVIAU6nGmxdoR2SSq5+xBh6vDs/+u/xz+Cn9LopXD26MbbCGXftg7aI4yMTYTras3wIUY2rWj6KjSqtsY709inLsvtln1sQUg03JlBO03P6Tkq3E2CIXuts8kMFt2448pO8lBr1X1eIOshWx9jr2oEqTmy40FYaYApkHIiriI8uZ5yjaC319HuUSQ4RFT1oNH61zojtzMMFO3iCM2xqkknfoA9ktyCtsrnFyhwM8vYkW/5Wbq7l6Bd+mwTeAhCBTrRLztBKIvaDGRKIEUfSfL2po+E0eYf3Y8HCCmt6E6WQDlSbl5ulfghj44KkdlP0Q=
after_success:
  - ./mvnw clean cobertura:cobertura coveralls:report
